"""Create OrderItem table

Revision ID: 0f45a5ab1e69
Revises: 1bbe521de752
Create Date: 2025-06-14 00:15:14.169536

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0f45a5ab1e69"
down_revision: Union[str, None] = "1bbe521de752"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tenants")
    op.drop_index(op.f("idx_conversation_order"), table_name="orders")
    op.drop_index(op.f("idx_whatsapp_order"), table_name="orders")
    op.drop_index(op.f("ix_orders_buyer_phone"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("idx_theme_tenant"), table_name="storefront_themes")
    op.drop_table("storefront_themes")
    op.drop_table("seller_profiles")
    op.drop_table("products")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_order_channel_meta_channel"), table_name="order_channel_meta"
    )
    op.drop_index(
        op.f("ix_order_channel_meta_order_id"), table_name="order_channel_meta"
    )
    op.drop_table("order_channel_meta")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_channel_meta",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("order_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "channel",
            postgresql.ENUM("whatsapp", "instagram", "storefront", name="channeltype"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("message_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("chat_session_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "user_response_log", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("order_channel_meta_order_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("order_channel_meta_pkey")),
    )
    op.create_index(
        op.f("ix_order_channel_meta_order_id"),
        "order_channel_meta",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_channel_meta_channel"),
        "order_channel_meta",
        ["channel"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("is_seller", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="users_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("image_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("seller_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "is_featured",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "show_on_storefront",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "show_on_whatsapp",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"], ["users.id"], name="products_seller_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="products_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "seller_profiles",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("store_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("slug", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("bio", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("logo_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("banner_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("seller_profiles_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("seller_profiles_pkey")),
        sa.UniqueConstraint(
            "slug",
            name=op.f("seller_profiles_slug_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "storefront_themes",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("tenant_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("is_default", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "colors",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "typography",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "layout",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "component_styles",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("storefront_themes_tenant_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("storefront_themes_pkey")),
    )
    op.create_index(
        op.f("idx_theme_tenant"), "storefront_themes", ["tenant_id"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("product_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("message_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("conversation_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("whatsapp_number", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("buyer_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("buyer_phone", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("buyer_email", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("buyer_address", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "total_amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "order_source",
            postgresql.ENUM("whatsapp", "website", "instagram", name="ordersource"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "confirmed",
                "processing",
                "shipped",
                "delivered",
                "cancelled",
                name="orderstatus",
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("seller_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("orders_product_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("orders_pkey")),
    )
    op.create_index(
        op.f("ix_orders_buyer_phone"), "orders", ["buyer_phone"], unique=False
    )
    op.create_index(
        op.f("idx_whatsapp_order"),
        "orders",
        ["whatsapp_number", "message_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_conversation_order"), "orders", ["conversation_id"], unique=False
    )
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("subdomain", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("custom_domain", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("settings", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "storefront_enabled", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("tenants_pkey")),
        sa.UniqueConstraint(
            "custom_domain",
            name=op.f("tenants_custom_domain_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "subdomain",
            name=op.f("tenants_subdomain_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
