"""Add tenant_id to all relevant models and create Tenant model

Revision ID: c28529718993
Revises: 9d223fcb84c1
Create Date: 2025-05-26 11:30:39.428561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c28529718993'
down_revision: Union[str, None] = '9d223fcb84c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('ai_config', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'ai_config', 'tenants', ['tenant_id'], ['id'])
    op.add_column('conversation_history', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'conversation_history', 'tenants', ['tenant_id'], ['id'])
    op.add_column('orders', sa.Column('seller_id', sa.UUID(), nullable=False))
    op.add_column('orders', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('orders', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('notification_sent', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('tracking_number', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_carrier', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('version', sa.Integer(), nullable=False))
    op.create_index('idx_order_created', 'orders', ['created_at'], unique=False)
    op.create_index('idx_order_seller', 'orders', ['seller_id'], unique=False)
    op.create_index('idx_order_status', 'orders', ['status'], unique=False)
    op.create_foreign_key(None, 'orders', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['seller_id'], ['id'])
    op.add_column('products', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('products', sa.Column('version', sa.Integer(), nullable=False))
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.create_index('idx_product_deleted', 'products', ['is_deleted'], unique=False)
    op.create_index('idx_product_featured', 'products', ['is_featured'], unique=False)
    op.create_index('idx_product_price', 'products', ['price'], unique=False)
    op.create_index('idx_product_seller', 'products', ['seller_id'], unique=False)
    op.create_index('idx_product_storefront', 'products', ['show_on_storefront'], unique=False)
    op.create_foreign_key(None, 'products', 'tenants', ['tenant_id'], ['id'])
    op.add_column('seller_profiles', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'seller_profiles', 'tenants', ['tenant_id'], ['id'])
    op.add_column('users', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'tenant_id')
    op.drop_constraint(None, 'seller_profiles', type_='foreignkey')
    op.drop_column('seller_profiles', 'tenant_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index('idx_product_storefront', table_name='products')
    op.drop_index('idx_product_seller', table_name='products')
    op.drop_index('idx_product_price', table_name='products')
    op.drop_index('idx_product_featured', table_name='products')
    op.drop_index('idx_product_deleted', table_name='products')
    op.alter_column('products', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('products', 'version')
    op.drop_column('products', 'tenant_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index('idx_order_status', table_name='orders')
    op.drop_index('idx_order_seller', table_name='orders')
    op.drop_index('idx_order_created', table_name='orders')
    op.drop_column('orders', 'version')
    op.drop_column('orders', 'shipping_carrier')
    op.drop_column('orders', 'tracking_number')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'notification_sent')
    op.drop_column('orders', 'is_deleted')
    op.drop_column('orders', 'tenant_id')
    op.drop_column('orders', 'seller_id')
    op.drop_constraint(None, 'conversation_history', type_='foreignkey')
    op.drop_column('conversation_history', 'tenant_id')
    op.drop_constraint(None, 'ai_config', type_='foreignkey')
    op.drop_column('ai_config', 'tenant_id')
    op.drop_table('tenants')
    # ### end Alembic commands ###
